name: Create Release

on:
  push:
    tags:
      - 'v*'  # triggers only when pushing tags like v1.0.0

jobs:
  release:
    name: Release on Tag
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up release assets
        run: |
          mkdir release-assets
          cp pihole-unbound-monitor.sh release-assets/
          cp README.md release-assets/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          files: release-assets/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
